# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  clone:
    machine:
      image: "ubuntu-2004:current"
    steps:
      - run:
          name: Clone
          command: ssh $SSH_USER@$SSH_HOST "cd /etc/BotYam && gh repo sync"
  deploy:
    machine:
        image: "ubuntu-2004:current"
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST "cd /etc/BotYam && docker-compose up -d --build"

workflows:
  clone-and-run:
    jobs:
      - clone:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - clone
          filters:
            branches:
              only: main